export const showcaseProjects = [
  {
    number: "01",
    title: "Prepzii",
    category: "EdTech Platform",
    short: "A premium JEE and NEET preparation workspace combining PYQs, mock tests, revision tools, performance analytics, and focused study workflows.",
    url: "https://www.prepzii.com/",
    image: "/images/prepzii-workspace-thumbnail.png",
    tags: ["EdTech", "Full-stack Platform", "Analytics"],
    tone: "from-violet-500/22",
    shape: "lg:col-span-12",
  },
  {
    number: "02",
    title: "Movie Explorer",
    category: "Entertainment Web App",
    short: "A polished movie discovery experience with search, genre filtering, ratings, release years, and watchlist-style browsing.",
    url: "https://movie-explorer-puce-ten.vercel.app/",
    image: "/images/movie-explorer-thumbnail.png",
    tags: ["React", "Movie Discovery", "Responsive UI"],
    tone: "from-fuchsia-500/20",
    shape: "lg:col-span-7",
  },
  {
    number: "03",
    title: "S.F Legal Firm",
    category: "Legal Services Website",
    short: "A professional legal firm website for Jharkhand clients, with service positioning, team presentation, and consultation calls to action.",
    url: "https://sflegalfirm.vercel.app/",
    image: "/images/sf-legal-firm-thumbnail.png",
    tags: ["Legal Website", "Brand Presence", "Lead Capture"],
    tone: "from-amber-500/18",
    shape: "lg:col-span-5",
  },
  {
    number: "04",
    title: "Heart Disease Analysis & Prediction",
    category: "Healthcare AI",
    short: "An interactive machine-learning application for exploring health indicators and generating a heart-disease risk prediction.",
    url: "https://heart-disease-prediction-app-ateebfatmi.streamlit.app/",
    image: "/images/heart-disease-graph-thumbnail.png",
    tags: ["Machine Learning", "Data Analysis", "Streamlit"],
    tone: "from-rose-500/22",
    shape: "lg:col-span-7",
  },
  {
    number: "05",
    title: "AI Grievance Routing System",
    category: "Workflow AI",
    short: "An AI system that automatically classifies public grievances and predicts the appropriate civic department with high accuracy.",
    url: "https://resolveai-grievance.streamlit.app/",
    image: "/images/ai-grievance-routing-civic-thumbnail.png",
    tags: ["NLP", "Classification", "Flask"],
    tone: "from-cyan-500/18",
    shape: "lg:col-span-5",
  },
  {
    number: "06",
    title: "Customer Support Chatbot",
    category: "Conversational AI",
    short: "An e-commerce support assistant built to respond to customer questions through a simple conversational interface.",
    url: "https://ecommerce-chatbot-app-zdwqzff4mefl5rgohvmi7z.streamlit.app/",
    image: "/images/customer-support-chatbot-thumbnail.png",
    tags: ["Chatbot", "Customer Support", "E-commerce"],
    tone: "from-violet-500/18",
    shape: "lg:col-span-12",
  },
  {
    number: "07",
    title: "Pizza Sales Analytics Dashboard",
    category: "Business Intelligence",
    short: "An interactive sales dashboard for exploring pizza-order performance, product trends, and business insights through clear visual reporting.",
    url: "https://data-analysis-pizza-sales.streamlit.app/",
    image: "/images/pizza-sales-graphs-thumbnail.png",
    tags: ["Sales Analytics", "Data Visualization", "Streamlit"],
    tone: "from-amber-500/18",
    shape: "lg:col-span-12",
  },
] as const;
